# Generated by Django 4.2.2 on 2023-06-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_example'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='other',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
